"""relationship added to roletable and usertable

Revision ID: 675c1cbe1789
Revises: 6ee52deb5108
Create Date: 2024-12-09 15:40:54.010337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675c1cbe1789'
down_revision: Union[str, None] = '6ee52deb5108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
