"""relationship added to roletable and usertable

Revision ID: 6ee52deb5108
Revises: c9f1e7f65bf5
Create Date: 2024-12-09 15:29:45.222137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ee52deb5108'
down_revision: Union[str, None] = 'c9f1e7f65bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_role_id_key', 'user_roles', type_='unique')
    op.drop_constraint('user_roles_user_id_key', 'user_roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_roles_user_id_key', 'user_roles', ['user_id'])
    op.create_unique_constraint('user_roles_role_id_key', 'user_roles', ['role_id'])
    # ### end Alembic commands ###
