"""adding coupons and distcount table

Revision ID: ad54d9744c9f
Revises: f4abb7fbcabd
Create Date: 2024-11-27 19:10:14.851239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad54d9744c9f'
down_revision: Union[str, None] = 'f4abb7fbcabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
