"""added some tables

Revision ID: bfbc5cadc01a
Revises: a9b5d94ecc6b
Create Date: 2024-12-31 07:34:17.047938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbc5cadc01a'
down_revision: Union[str, None] = 'a9b5d94ecc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_messages', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('chat_messages', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('chat_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.create_foreign_key(None, 'chat_messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.alter_column('chat_messages', 'message',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('chat_messages', 'conversation_id')
    op.drop_column('chat_messages', 'is_read')
    op.drop_column('chat_messages', 'file_type')
    op.drop_column('chat_messages', 'file_url')
    op.drop_column('chat_messages', 'agent_id')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
