"""changes in roletable and usertable

Revision ID: c9f1e7f65bf5
Revises: 021b509fdfc0
Create Date: 2024-12-06 19:55:39.097009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f1e7f65bf5'
down_revision: Union[str, None] = '021b509fdfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('user_roles', sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'user_roles', ['role_id'])
    op.create_unique_constraint(None, 'user_roles', ['user_id'])
    op.create_foreign_key(None, 'user_roles', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.drop_column('user_roles', 'assigned_at')
    op.drop_column('user_roles', 'assigned_by')
    # ### end Alembic commands ###
