"""changes in roletable and usertable

Revision ID: fe4a4c18b338
Revises: 675c1cbe1789
Create Date: 2024-12-09 18:24:59.842665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4a4c18b338'
down_revision: Union[str, None] = '675c1cbe1789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
